# Generated by Django 2.2.24 on 2021-06-16 02:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('originalName', models.CharField(max_length=100)),
                ('nameInSpain', models.CharField(blank=True, max_length=100, null=True)),
                ('year', models.PositiveSmallIntegerField(default=2021, validators=[django.core.validators.MinValueValidator(1895)])),
                ('director', models.CharField(max_length=50)),
                ('duration', models.PositiveSmallIntegerField()),
                ('sinopsis', models.TextField(default='Breve resumen de la trama')),
                ('genres', models.CharField(max_length=100)),
                ('rate', models.PositiveSmallIntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=0)),
            ],
        ),
    ]
